- name: delete_all_code
  hosts: all
  # vars:
  #   stationId: '{{ station_id }}'
  #   type: '{{ prd_type }}'
    
  tasks:
    - name: Get the PID of running process
      ignore_errors: yes
      shell: "ps -few | grep check_infiniti_loop.py | awk '{print $2}'"
      register: running_processes

    - name: '결과를 출력합니다.'
      debug: var=running_processes.stdout.split('\n')

    - set_fact:
      count: "{{ running_processes.stdout.split('\n') | length }}"

    
    - name: '결과를 출력합니다.'
      debug: var=count




    # - name: kill proccess
    #   shell: echo $(ps ax | grep OPST | awk '{print $1}' | xargs kill)
    #   register: result
    #   ignore_errors: yes
    # - name: kill proccess
    #   shell: echo $(ps ax | grep APT | awk '{print $1}' | xargs kill)
    #   register: result
    #   ignore_errors: yes
    # - name: kill proccess
    #   shell: echo $(ps ax | grep OR | awk '{print $1}' | xargs kill)
    #   register: result
    #   ignore_errors: yes

    # - name: '결과를 출력합니다.'
    #   debug: var=result.stdout.split('\n')
     
  
    # - name: delete directory OPST
    #   shell: 'rm -rf *_OPST'  
    #   register: result
    #   args: 
    #     chdir: '/root/station_list'
    # - name: '결과를 출력합니다.'
    #   debug: var=result.stdout.split('\n')
    
      
    # - name: delete directory APT
    #   shell: 'rm -rf *_APT'  
    #   register: result
    #   args: 
    #     chdir: '/root/station_list'
    # - name: '결과를 출력합니다.'
    #   debug: var=result.stdout.split('\n')
      
    # - name: delete directory OR
    #   shell: 'rm -rf *_OR'  
    #   register: result
    #   args: 
    #     chdir: '/root/station_list'
    # - name: '결과를 출력합니다.'
    #   debug: var=result.stdout.split('\n')
      
