- name: create_all_process
  hosts: '{{ node }}'
  vars:
    stationId: '{{ station_id }}'
    type: '{{ prd_type }}'

  tasks:
    - name: play reload_proceess
      shell: "python reload_one_process.py {{ stationId }} {{ type }}"
      args: 
        chdir: '/root'
      register: result
    
    - name: '결과를 출력합니다.'
      debug: var=result.stdout.split('\n')


     
