- name: run python code
  hosts: python_a
  vars:
    min_cnt: "{{ min_cnt }}"
  
  tasks:
    - name: get que count
      shell: 'cat que.txt |wc -l'  
      register: cnt_a
    

    - set_fact:
        cnt_a: "{{ cnt_a.stdout }}"

    - name: '결과를 출력합니다.'
      debug: var=cnt_a

    - name: '현재 저장된 최소값입니다.'
      debug: var=min_cnt

    - set_fact:
        min_cnt: "{{ cnt_a.stdout }}"

#     - name: '현재 저장된 최소값입니다.'
#       debug: var=min_cnt
#       when: "{{ cnt_a }}" > "{{ min_cnt }}"

#       {% if cnt_a > min_cnt%}
# df -h
# {% endif %}
      
