- name: run python code
  hosts: python_a
  vars:
    stationId: '{{ station_id }}'
    type: '{{ prd_type }}'  

  
  tasks:
    - name: check dir
      stat:
        path: '/root/station_list/{{ stationId }}_{{ type }}'
      register: my_folder

    - set_fact:
        exists: "{{ my_folder.stat.exists }}"



    - name: Play cat que len
      block:
        - name: get que count
          shell: 'cat que.txt |wc -l'  
          register: cnt_a

        - set_fact:
            cnt: "{{ cnt_a.stdout }}"
        
      when: exists == false

    # - name: '결과를 출력합니다.'
    #   debug: var=cnt




#     - name: '현재 저장된 최소값입니다.'
#       debug: var=min_cnt
#       when: "{{ cnt_a }}" > "{{ min_cnt }}"

#       {% if cnt_a > min_cnt%}
# df -h
# {% endif %}
      
