- name: run python code
  hosts: python_c
    
  vars:
    min_cnt: "{{ min_cnt }}"
  
  tasks:
    - name: get que count
      shell: 'cat que.txt |wc -l'  
      register: cnt_c
    

    - set_fact:
        cnt: "{{ cnt_c.stdout }}"

    - name: '결과를 출력합니다.'
      debug: var=cnt


#     - name: '현재 저장된 최소값입니다.'
#       debug: var=min_cnt
#       when: "{{ cnt_a }}" > "{{ min_cnt }}"

#       {% if cnt_a > min_cnt%}
# df -h
# {% endif %}
      
