- name: run python code
  hosts: localhost

    
  tasks:
    - name: "python_a의 que 값"
      debug:
        var: hostvars['python_a']['cnt']

    - set_fact:
        cnt_a: "{{ hostvars['python_a']['cnt'] }}"

    - name: "딕셔너리 추가"
      set_fact:
        nodes: "{{ nodes|default([]) + [ {'node': 'python_a', 'que_len': cnt_a|int} ] }}"


    - name: "python_b의 que 값"
      debug:
        var: hostvars['python_b']['cnt']

    - set_fact:
        cnt_b: "{{ hostvars['python_b']['cnt'] }}"


    - name: "딕셔너리 추가"
      set_fact:
        nodes: "{{ nodes|default([]) + [ {'node': 'python_b', 'que_len': cnt_b|int} ] }}"

    - name: "python_c의 que 값"
      debug:
        var: hostvars['python_c']['cnt']

    - set_fact:
        cnt_c: "{{ hostvars['python_c']['cnt'] }}"

    - name: "딕셔너리 추가"
      set_fact:
        nodes: "{{ nodes|default([]) + [ {'node': 'python_c', 'que_len': cnt_c|int} ] }}"


    - name: "nodes의 값"
      debug:
        var: nodes

    - name: "최솟값을 가진 노드입니다."
      debug:
        msg: "{{ (nodes |sort(attribute='que_len'))[0]['node'] }}"

      
    - set_fact:
        min_node: "{{ (nodes |sort(attribute='que_len'))[0]['node'] }}"
    

